### PR TITLE
QAvatar

### PR DESCRIPTION
**Pull request by krthr**

### CODE REVIEW

**Comment by krthr** [comment]
Hey! This ext is so usefull. 

I have added the new Quasar v1 component: [QAvatar](https://v1.quasar-framework.org/vue-components/avatar)

**Comment by Abdelaziz18003** [comment]
Hey @krthr, Thanks for your interest in contributing to this extension. First, I apologize for being late to respond. I reviewed your commit and it is almost perfect. There is just one thing missing which is cursor positioning.
```
"<q-avatar color=\"red\" text-color=\"white\" icon=\"directions\" />"
```
You can adjust it like that:
```
"<q-avatar color=\"${1:red}\" text-color=\"${2:white}\" icon=\"${3:directions}\" />"
```

My main focus now is to finish adding the `v0.17.x` components (which is almost done) and release them. Then I will merge this PR and start adding the new components of `v1.0`. Thanks for your time and effort :heart:

**Comment by krthr** [comment]
Hey! Oky. I will add the correction

**Comment by Abdelaziz18003** [comment]
quasar v1 components including QAvatar are added. Closing as it is now conflicting with the current master branch.

**Pull request closed without merging**
