### PR TITLE
Cristalt

### PR DESCRIPTION
**Pull request by CristalT**

### CODE REVIEW

**Review by Abdelaziz18003 — CHANGES_REQUESTED** [review]
Hi @CristalT and thanks for your interest in making Quasar Snippets better and contributing to it :heart:.
Here are few things that will be nice if you fix them before merging your PR.

1. There is no need for a package-lock.json file since we don't have any dependencies in this project.
2. There are some indentation problems inside snippets/sinppets.json file. It looks like it is caused by your editor auto-formatter. Some levels are indented with 4 spaces. Please make sure that indentation is consistent across all the file and and that is equal to 2 spaces.
3. It will be nice to add "icon" property to QTab.
4. It will be nice to add "icon" & "exact" to QRouteTab since they are needed in most cases.
5. QTable is not part of tabs so it will nice to remove it for now. We will add it later with other related components like "QTh", "QTd" .. etc.
6. Let's keep the same order of the official documentation. So the new added Snippets should be placed after QBtnDropdown and before QField because they are parts of Navigation section.
7. Feel free to add other navigation section components if you want they are not added yet :)

**Comment by CristalT** [comment]
Thanks for your suggestions @Abdelaziz18003. Are welcome for me. Sorry by my untidiness. Anxious to collaborate I had many mistakes. I am working in your requests and adding some others components.

**Comment by Abdelaziz18003** [comment]
@CristalT you and your PR are welcome, and I am happy to see you contributing. I was traveling this last week so I couldn't work on it. I will be adding more components the next days. If you have some work done you can update your PR and I will merge it.

**Comment by Abdelaziz18003** [comment]
this PR is redundant now. closing.

**Pull request closed without merging**
